name: Docker

on:
  pull_request:
    branches-ignore:
      - "renovate/**"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.event.repository.name }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ghcr.io/rinsuki/sniproxy
          tags: |
            type=ref,event=branch
            type=sha
      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
